spring:
  application:
    name: camel-microservice-a
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
camel:
  component:
    kafka:
      brokers: localhost:9092

app:
  dynamic-routes:
    even: 'activemq:even-route'
    odd: 'activemq:odd-route'